version: "3"

services:
  playit:
    container_name: "playit"
    image: bartosz11/playit-docker:latest
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
    volumes:
      - config:/home/container

volumes:
    config:
